version: '3.5'
services:
  executor:
    image: scalify/puppet-master-executor
    restart: always
    networks:
      - puppet_master
    environment:
      - "NODE_ENV=prod"
      - "QUEUE_HOST=queue"
      - "QUEUE_PORT=5672"
      - "QUEUE_USERNAME=puppet"
      - "QUEUE_PASSWORD=puppet"

  gateway:
    image: scalify/puppet-master-gateway
    restart: always
    networks:
      - puppet_master
    environment:
      - "COUCH_DB_HOST=database"
      - "COUCH_DB_PORT=5984"
      - "COUCH_DB_USERNAME=puppet"
      - "COUCH_DB_PASSWORD=puppet"
      - "QUEUE_HOST=queue"
      - "QUEUE_PORT=5672"
      - "QUEUE_USERNAME=puppet"
      - "QUEUE_PASSWORD=puppet"
      - "VERBOSE=false"
      - "LISTEN_PORT=80"
      - "API_TOKEN=puppet"
    command: "gateway"
    ports:
      - "80:80"

  database:
    image: couchdb:2.2
    volumes:
      - "./data/database:/opt/couchdb/data"
    restart: always
    networks:
      - puppet_master
    environment:
      - "COUCHDB_USER=puppet"
      - "COUCHDB_PASSWORD=puppet"
    ports:
      - "127.0.0.1:5984:5984"

  queue:
    image: rabbitmq:3.7.7-management-alpine
    environment:
      - "RABBITMQ_DEFAULT_USER=puppet"
      - "RABBITMQ_DEFAULT_PASS=puppet"
    volumes:
      - "./data/queue:/var/lib/rabbitmq"
    expose:
      - "5672"
    restart: always
    networks:
      - puppet_master
    ports:
      - "127.0.0.1:15672:15672"

networks:
  default: {}
  puppet_master:
    external: false
    name: puppet_master
